# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeAnswer',
            new_name='AnswerLike',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='creation_date',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='text',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='answer',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=b'/static/images/sample.jpg', upload_to=b'/uploads/images/%Y-%m-%d'),
        ),
    ]
