# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20170124_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=b'static/img/no-avatar.png', upload_to=b'/home/serych/Technopark/Technopark_Web/Django/ask_govjazin/uploads'),
        ),
    ]
