# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20170124_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data',
            field=models.CharField(max_length=420),
        ),
    ]
